#include "ToColor.h"
#include <map>


using td::ColorID;



td::ColorID to_color(std::string str) {
    for (char& c : str)
        c = std::tolower(c);

    static std::map<std::string, ColorID> string_to_color_map = {
        {"maroon", ColorID::Maroon},
        {"darkred", ColorID::DarkRed},
        {"brown", ColorID::Brown},
        {"firebrick", ColorID::Firebrick},
        {"crimson", ColorID::Crimson},
        {"red", ColorID::Red},
        {"tomato", ColorID::Tomato},
        {"coral", ColorID::Coral},
        {"indianred", ColorID::IndianRed},
        {"lightcoral", ColorID::LightCoral},
        {"darksalmon", ColorID::DarkSalmon},
        {"salmon", ColorID::Salmon},
        {"lightsalmon", ColorID::LightSalmon},
        {"orangered", ColorID::OrangeRed},
        {"darkorange", ColorID::DarkOrange},
        {"orange", ColorID::Orange},
        {"gold", ColorID::Gold},
        {"darkgoldenrod", ColorID::DarkGoldenRod},
        {"goldenrod", ColorID::GoldenRod},
        {"palegoldentod", ColorID::PaleGoldenTod},
        {"darkkhaki", ColorID::DarkKhaki},
        {"khaki", ColorID::Khaki},
        {"olive", ColorID::Olive},
        {"yellow", ColorID::Yellow},
        {"yellowgreen", ColorID::YellowGreen},
        {"darkolivegreen", ColorID::DarkOliveGreen},
        {"olivedrab", ColorID::OliveDrab},
        {"lawngreen", ColorID::LawnGreen},
        {"chartreuse", ColorID::Chartreuse},
        {"greenyellow", ColorID::GreenYellow},
        {"darkgreen", ColorID::DarkGreen},
        {"green", ColorID::Green},
        {"forestgreen", ColorID::ForestGreen},
        {"lime", ColorID::Lime},
        {"limegreen", ColorID::LimeGreen},
        {"lightgreen", ColorID::LightGreen},
        {"palegreen", ColorID::PaleGreen},
        {"darkseagreen", ColorID::DarkSeaGreen},
        {"mediumspringgreen", ColorID::MediumSpringGreen},
        {"springgreen", ColorID::SpringGreen},
        {"seagreen", ColorID::SeaGreen},
        {"mediumaquamarine", ColorID::MediumAquaMarine},
        {"mediumseagreen", ColorID::MediumSeaGreen},
        {"lightseagreen", ColorID::LightSeaGreen},
        {"darkslategray", ColorID::DarkSlateGray},
        {"teal", ColorID::Teal},
        {"darkcyan", ColorID::DarkCyan},
        {"cyan", ColorID::Cyan},
        {"lightcyan", ColorID::LightCyan},
        {"darkturquoise", ColorID::DarkTurquoise},
        {"turquoise", ColorID::Turquoise},
        {"mediumturquoise", ColorID::MediumTurquoise},
        {"paleturquoise", ColorID::PaleTurquoise},
        {"aquamarine", ColorID::AquaMarine},
        {"powderblue", ColorID::PowderBlue},
        {"cadetblue", ColorID::CadetBlue},
        {"steelblue", ColorID::SteelBlue},
        {"cornflowerblue", ColorID::CornFlowerBlue},
        {"deepskyblue", ColorID::DeepSkyBlue},
        {"dodgerblue", ColorID::DodgerBlue},
        {"lightblue", ColorID::LightBlue},
        {"skyblue", ColorID::SkyBlue},
        {"lightskyblue", ColorID::LightSkyBlue},
        {"midnightblue", ColorID::MidnightBlue},
        {"navy", ColorID::Navy},
        {"darkblue", ColorID::DarkBlue},
        {"mediumblue", ColorID::MediumBlue},
        {"blue", ColorID::Blue},
        {"royalblue", ColorID::RoyalBlue},
        {"blueviolet", ColorID::BlueViolet},
        {"indigo", ColorID::Indigo},
        {"darkslateblue", ColorID::DarkSlateBlue},
        {"slateblue", ColorID::SlateBlue},
        {"mediumslateblue", ColorID::MediumSlateBlue},
        {"mediumpurple", ColorID::MediumPurple},
        {"darkmagenta", ColorID::DarkMagenta},
        {"darkviolet", ColorID::DarkViolet},
        {"darkorchid", ColorID::DarkOrchid},
        {"mediumorchid", ColorID::MediumOrchid},
        {"purple", ColorID::Purple},
        {"thistle", ColorID::Thistle},
        {"plum", ColorID::Plum},
        {"violet", ColorID::Violet},
        {"magenta", ColorID::Magenta},
        {"orchid", ColorID::Orchid},
        {"mediumvioletred", ColorID::MediumVioletRed},
        {"palevioletred", ColorID::PaleVioletRed},
        {"deeppink", ColorID::DeepPink},
        {"hotpink", ColorID::HotPink},
        {"lightpink", ColorID::LightPink},
        {"pink", ColorID::Pink},
        {"antiquewhite", ColorID::AntiqueWhite},
        {"beige", ColorID::Beige},
        {"bisque", ColorID::Bisque},
        {"blanchedalmond", ColorID::BlanchedAlmond},
        {"wheat", ColorID::Wheat},
        {"cornsilk", ColorID::CornSilk},
        {"lemonchiffon", ColorID::LemonChiffon},
        {"lightgoldenrodyellow", ColorID::LightGoldenRodYellow},
        {"lightyellow", ColorID::LightYellow},
        {"saddlebrown", ColorID::SaddleBrown},
        {"sienna", ColorID::Sienna},
        {"chocolate", ColorID::Chocolate},
        {"peru", ColorID::Peru},
        {"sandybrown", ColorID::SandyBrown},
        {"burlywood", ColorID::BurlyWood},
        {"tan", ColorID::Tan},
        {"rosybrown", ColorID::RosyBrown},
        {"moccasin", ColorID::Moccasin},
        {"navajowhite", ColorID::NavajoWhite},
        {"peachpuff", ColorID::PeachPuff},
        {"mistyrose", ColorID::MistyRose},
        {"lavenderblush", ColorID::LavenderBlush},
        {"linen", ColorID::Linen},
        {"oldlace", ColorID::OldLace},
        {"papayawhip", ColorID::PapayaWhip},
        {"seashell", ColorID::SeaShell},
        {"mintcream", ColorID::MintCream},
        {"slategray", ColorID::SlateGray},
        {"lightslategray", ColorID::LightSlateGray},
        {"lightsteelblue", ColorID::LightSteelBlue},
        {"lavender", ColorID::Lavender},
        {"floralwhite", ColorID::FloralWhite},
        {"aliceblue", ColorID::AliceBlue},
        {"ghostwhite", ColorID::GhostWhite},
        {"honeydew", ColorID::Honeydew},
        {"ivory", ColorID::Ivory},
        {"azure", ColorID::Azure},
        {"snow", ColorID::Snow},
        {"black", ColorID::Black},
        {"dimgray", ColorID::DimGray},
        {"gray", ColorID::Gray},
        {"darkgray", ColorID::DarkGray},
        {"silver", ColorID::Silver},
        {"lightgray", ColorID::LightGray},
        {"gainsboro", ColorID::Gainsboro},
        {"whitesmoke", ColorID::WhiteSmoke},
        {"white", ColorID::White},
        {"syslabel", ColorID::SysLabel},
        {"sysheadertext", ColorID::SysHeaderText},
        {"systext", ColorID::SysText},
        {"sysselectedtext", ColorID::SysSelectedText},
        {"systransparentselection", ColorID::SysTransparentSelection},
        {"syscontroltext", ColorID::SysControlText},
        {"syslabelhighlight", ColorID::SysLabelHighlight},
        {"syscritical", ColorID::SysCritical},
        {"sysconstructive", ColorID::SysConstructive},
        {"sysdestructive", ColorID::SysDestructive},
        {"transparent", ColorID::Transparent},
    };

    auto it = string_to_color_map.find(str);
    if (it != string_to_color_map.end()) {
        return it->second;
    }
    else {
        return ColorID::Black;
    }
}
